### ISSUE TITLE
Problem implementing same code in Swift

### ISSUE THREAD

**Issue by alvinvarghese** [slcott/Tree#1]
Would you mind helping me out a little, I have converted the same project in Swift, it works but does not showing any cells. It is not even calling cellForItemAtIndex.

Please?

**Comment by scott-cognitiv** [comment]
It should not matter which language you choose: swift or obj-c. They both call UIKit. You have an error in your code. I suggest stepping through my code and stepping through your code and try to use divide and conquer debugging to identify where your code is failing.

**Comment by slcott** [comment]
It should not matter which language you choose: swift or obj-c. They both call UIKit. You have an error in your code. I suggest stepping through my code and stepping through your code and try to use divide and conquer debugging to identify where your code is failing.
